# Generated by Django 5.1 on 2024-09-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenamiento', models.CharField(choices=[('fuerza', 'fuerza'), ('resistencia', 'resistencia'), ('velocidad', 'velocidad'), ('potencia', 'potencia')], max_length=20)),
                ('dias', models.CharField(choices=[('1 a 3 dias', '1 a 3 dias'), ('3 a 5 dias', '3 a 5 dias'), ('5 a 7 dias', '5 a 7 dias')], max_length=20)),
                ('horas', models.CharField(choices=[('menos de una hora', 'menos de una hora'), ('una a dos horas', 'una a dos horas'), ('mas de dos horas', 'mas de dos horas')], max_length=30)),
            ],
        ),
    ]
