# Generated by Django 5.1 on 2024-09-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'verbose_name': 'Categoria de Producto', 'verbose_name_plural': 'Categorias de Productos'},
        ),
    ]
