# Generated by Django 5.1 on 2024-09-10 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_pais_apellido'),
        ('productos', '0002_alter_productocategoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='deporte',
            field=models.CharField(blank=True, choices=[('F', 'Futbol'), ('R', 'Rugby'), ('B', 'Basquet'), ('T', 'Tenis'), ('A', 'Atletismo')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AtletaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atleta_productos', to='atletas.pais')),
                ('producto_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_atletas', to='productos.productocategoria')),
            ],
            options={
                'verbose_name': 'Atleta Producto',
                'verbose_name_plural': 'Atletas Productos',
            },
        ),
    ]
