# Generated by Django 5.1 on 2024-09-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_alter_pais_deporte_atletaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='grasa',
            field=models.CharField(blank=True, choices=[('6-13%', '6-13%'), ('14-17%', '14-17%'), ('18-24%', '18-24%'), ('25% o mas', '25% o mas')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AtletaProducto',
        ),
    ]
