# Generated by Django 5.1 on 2024-09-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0006_pais_grasa_delete_atletaproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Atleta'},
        ),
        migrations.AddField(
            model_name='pais',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
