# Generated by Django 5.1 on 2024-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0007_alter_pais_options_pais_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='edad',
        ),
        migrations.AddField(
            model_name='pais',
            name='nivel',
            field=models.CharField(blank=True, choices=[('P', 'Profesional'), ('S', 'Semi-Profesional'), ('A', 'Amateur'), ('I', 'Principiante')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='deporte',
            field=models.CharField(blank=True, choices=[('F', 'Futbol'), ('R', 'Rugby'), ('B', 'Basquet'), ('T', 'Tenis'), ('A', 'Atletismo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='grasa',
            field=models.CharField(blank=True, choices=[('6-13%', '6-13%'), ('14-17%', '14-17%'), ('18-24%', '18-24%'), ('25% o más', '25% o más')], max_length=10, null=True),
        ),
    ]
