# Generated by Django 5.1 on 2024-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0008_remove_pais_edad_pais_nivel_alter_pais_deporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('P', 'Profesional'), ('SP', 'Semi-Profesional'), ('A', 'Amateur'), ('I', 'Principiante')], max_length=2)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('marca_buena_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marca_buena_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marca_normal_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marca_normal_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marca_mala_min', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
