# Generated by Django 5.1 on 2024-09-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0009_testspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='test_speed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atletas.testspeed'),
        ),
    ]
