# Generated by Django 5.1 on 2024-09-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0011_remove_pais_test_speed_remove_pais_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='velocidad',
            field=models.CharField(blank=True, choices=[(' 4.6 - 4.9 segundos', 'Bueno'), ('5.0 - 5.3 segundos', 'Normal'), ('5.4 segundos o más', 'Malo')], max_length=100, null=True),
        ),
    ]
