# Generated by Django 5.1 on 2024-09-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0014_alter_pais_options_alter_pais_grasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='deporte',
            field=models.CharField(blank=True, choices=[('Futbol', 'Futbol'), ('Rugby', 'Rugby'), ('Basquet', 'Basquet'), ('Tenis', 'Tenis'), ('Atletismo', 'Atletismo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='grasa',
            field=models.CharField(blank=True, choices=[('6-13%', '6-13%'), ('14-17%', '14-17%'), ('18-24%', '18-24%'), ('25% o mas', '25% o mas')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='velocidad',
            field=models.CharField(blank=True, choices=[('4.6 - 4.9 segundos', ' 4.6 - 4.9 segundos'), ('5.0 - 5.3 segundos', '5.0 - 5.3 segundos'), ('5.4 segundos o más', '5.4 segundos o más')], max_length=20, null=True),
        ),
    ]
